### ISSUE TITLE
Incompatibility with HA 0.113.0

### ISSUE THREAD

**Issue by agneevX** [N-l1/lovelace-soft-ui#17]
After updating to v0.113.0, the background of the card is showing for some reason. 

<img width="736" alt="image" src="https://user-images.githubusercontent.com/19761269/88264250-16c9ed80-cce9-11ea-9b27-24d937100ac9.png">

```yaml
content: |
  # Bedroom
style:
  .: |
    ha-card {
      --paper-card-background-color: none !important;
      box-shadow: none !important;
    }
  ha-markdown:
    $: |
      h1 {
        font-size: 20px;
        font-weight: bold;
        font-family: Helvetica;
        letter-spacing: '-0.01em';
      }
type: markdown
```
