### ISSUE TITLE
Theme not updating correctly with Chrome in dark mode

### ISSUE THREAD

**Issue by backslashV** [N-l1/lovelace-soft-ui#41]
Hi,
I have dark theme set for Windows and as such, Chrome is always in dark mode. I have set the automation mentioned in the setup to switch between the light and dark themes depending on the sun's position. However, during the day, light theme is not displayed correctly and is basically dark with light shadows:
![image](https://user-images.githubusercontent.com/8752221/106345813-b3a4af00-6267-11eb-907b-8c265a50d13b.png)
Is there a way around this?
By the way, "Backend-selected" is selected under profile>Theme

Thanks

**Comment by N-l1** [comment]
In your case, since Chrome remains in dark theme, you would need to set up a manual automation switching between themes. Check the Alternative Automation section in the Theme Automation section.

**Comment by KTibow** [comment]
I think you need to do the regular setup method.

**Comment by backslashV** [comment]
> In your case, since Chrome remains in dark theme, you would need to set up a manual automation switching between themes. Check the Alternative Automation section in the Theme Automation section.

The Alternative Automation is what I currently have.

**Comment by backslashV** [comment]
> I think you need to do the regular setup method, if you want to change themes based on system dark mode.

Could you clarify what you mean by regular setup?

**Comment by N-l1** [comment]
@backslashV did you use the blueprint or the automation? Would you mind sharing your code. Thanks

**Comment by backslashV** [comment]
> @backslashV did you use the blueprint or the automation? Would you mind sharing your code. Thanks

I used the automation.
```
alias: Set theme
description: Set light/dark theme at sunrise/sunset
trigger:
  - platform: homeassistant
    event: start
  - platform: state
    entity_id: sun.sun
action:
  - choose:
      - conditions:
          - condition: state
            entity_id: sun.sun
            state: above_horizon
        sequence:
          - service: frontend.set_theme
            data:
              name: clear
      - conditions:
          - condition: state
            entity_id: sun.sun
            state: below_horizon
        sequence:
          - service: frontend.set_theme
            data:
              name: slate
mode: single
```

**Comment by N-l1** [comment]
It seems like you would need to use this instead:

```yaml
- alias: Set theme
  description: Set light/dark theme at sunrise/sunset
  trigger:
    - platform: homeassistant
      event: start
    - platform: state
      entity_id: sun.sun
  action:
    - choose:
        - conditions:
            - condition: state
              entity_id: sun.sun
              state: above_horizon
          sequence:
            - service: frontend.set_theme
              data:
                name: clear
        - conditions:
            - condition: state
              entity_id: sun.sun
              state: below_horizon
          sequence:
            - service: frontend.set_theme
              data:
                name: slate
  mode: single
```

**Comment by backslashV** [comment]
Oh. I pasted the YAML from the automations page not from automations.yaml.

**Comment by N-l1** [comment]
Interesting. Do you want the theme to stay dark on the Windows machine or do you want it to switch to a light theme during the day? If the themes are installed and the automation is set up properly. The Clear theme should be set during the day and the Slate theme should be set during the night regardless if the system is always in dark mode. Are the themes in the APP custom themes or default HA themes? I would encourage you to try out @KTibow 's [blueprint](https://community.home-assistant.io/t/light-dark-theme-switcher-based-on-sun/255455)

**Comment by backslashV** [comment]
Yes, light theme during the day and dark at night. The two themes are located in config/themes/.
I just tried the blueprint and the issue persists. I manually set `sun.sun` to `above_horizon` and the theme stayed dark but the shadows got white.

**Comment by N-l1** [comment]
You said that on the APP it works, is it just the default HA themes or the custom ones? Can you also try setting your themes manually via the Developer Tools?

**Comment by backslashV** [comment]
The app just mirrors whatever theme I've set on desktop and they are the same custom ones: clear and slate. Setting theme from developer tools doesn't seem to do anything. 
![image](https://user-images.githubusercontent.com/8752221/106350715-e6f93500-628b-11eb-9488-b06add76476c.png)

Changing the theme from profile>Theme works though.

**Comment by N-l1** [comment]
That would be why your automations don't work. Developer tools should be able to set the themes. Make sure you have the right theme and the exact same name (case sensitive) matching with what is in the theme YAML. Try reinstalling the theme, restarting, and refreshing.

**Comment by backslashV** [comment]
Setting the theme through developer tools works fine in the Android app. When I set the light theme there, the app UI reflects my selection, but Chrome on desktop and the iOS app still show the dark theme. Interestingly, when I do the same in developer tools on the iPad app or Chrome, their UI doesn't update, but the Android app's does.

**Comment by N-l1** [comment]
Can you make sure again you have the Backend-selected option set for you desktop and iOS user.

**Comment by backslashV** [comment]
Yes, Backend-selected is chosen everywhere.

**Comment by backslashV** [comment]
I just found out something. When I select "Light" from Windows settings, Chrome behaves fine and responds to theme changes. When Windows is set to Dark, HA behaves that way. Maybe, it's a Chrome issue and the way it renders colors based on its own theme.

**Comment by N-l1** [comment]
You are right! I just tested it out on my Windows machine. It was working fine before, however, as soon as I set a default `mode: dark` theme. The device would be "stuck" in the dark theme so long my system was in the dark mode. I think to solve this problem we would just have to figure out a way to undo or disable the HA automatic [dark mode](https://www.home-assistant.io/blog/2020/08/12/release-114/) function...

**Comment by KTibow** [comment]
I think if you call the service two times, once with `mode: light` and once with `mode: dark` it might work. Just guessing though.

**Comment by backslashV** [comment]
> You are right! I just tested it out on my Windows machine. It was working fine before, however, as soon as I set a default `mode: dark` theme. The device would be "stuck" in the dark theme so long my system was in the dark mode. I think to solve this problem we would just have to figure out a way to undo or disable the HA automatic [dark mode](https://www.home-assistant.io/blog/2020/08/12/release-114/) function...
> 
> Edit: This seems to be exactly because of the issue [here](https://github.com/home-assistant/frontend/issues/6611), however, there doesn't seem to be a fix 😕

Precisely.

**Comment by backslashV** [comment]
> I think if you call the service two times, once with `mode: light` and once with `mode: dark` it might work. Just guessing though.

Nope, it doesn't work.

**Comment by KTibow** [comment]
Actually, I think we've gotten distracted from the main subject
> light theme is not displayed correctly and is basically dark with light shadows

I can help you with this. First of all, what themes are you using?

**Comment by backslashV** [comment]
I am using the clear and the slate themes. I believe you want to modify the box-shadow element of the CSS code which is based on the sun's position?

**Comment by KTibow** [comment]
Okay. Could you post the source code of the themes? I'll modify them, and then you can paste the code back in. This will require you to change the code in all of your cards.

**Comment by N-l1** [comment]
I think @backslashV's problem is just with theme switching. @backslashV's machine is always in a system dark mode, hence HA is always using the dark mode theme. However @backslashV would like to use the Clear theme during the day. I think everytime the automation sets the theme, by specifying that the theme is both for dark and light mode should temperarily solve the issue:
```yaml
- id: theme_routine
  alias: Theme Routine
  description: "Theme routine."
  trigger:
  - platform: homeassistant
    event: start
  - platform: state
    entity_id: sun.sun
  action:
  - choose:
    - conditions:
      - condition: state
        entity_id: sun.sun
        state: "above_horizon"
      sequence:
      - service: frontend.set_theme
        data:
          name: clear
          mode: light
      - service: frontend.set_theme
        data:
          name: clear
          mode: dark
    - conditions:
      - condition: state
        entity_id: sun.sun
        state: "below_horizon"
      sequence:
      - service: frontend.set_theme
        data:
          name: slate
          mode: light
      - service: frontend.set_theme
        data:
          name: slate
          mode: dark
```
