### ISSUE TITLE
Resolution issues

### ISSUE THREAD

**Issue by filikun** [N-l1/lovelace-soft-ui#7]
Hey, awesome style! I have a problem with resolutions though. My GF have a Samsung Galaxy S10e with a smaller display and you can see for yourself that the buttons get cropped. Is there any way around this? I'm no expert in with styling so I'm not sure what I can do.

https://imgur.com/a/T0Vixpr

**Comment by N-l1** [comment]
Thank you! I am aware of this problem and it is something I am planning to improve. However, I’m quite busy at the moment so don’t expect it too soon. 

The simplest solution is to remove the fifth card.

It has been also mentioned [on the forums](https://community.home-assistant.io/t/lovelace-soft-ui-simple-and-clean-lovelace-configuration/159357/63)

**Comment by KTibow** [comment]
Thanks for the fix! I've noticed on bigger displays, it isn't centered in the middle though too. Thanks for all of your work in Soft UI!
[![The buttons are aligned to the left...](https://user-images.githubusercontent.com/10727862/82160474-8388bd80-984a-11ea-91b5-139de89ccd13.png)](#)

**Comment by N-l1** [comment]
Okay @KTibow, thanks for letting me know! 👍

**Comment by KTibow** [comment]
Would this work if you used percentages instead of pixels?

**Comment by N-l1** [comment]
Yes! Don't know why I didn't think of that. Would you like to do some testing @KTibow?

**Comment by KTibow** [comment]
I can try that out. I'm worried that it might not end up being square, though.  
If the width is `10%` of the **width of the bigger** horizontal arrangement, the height needs to be `10%` of the **width of the bigger** horizontal arrangement, not `10%` of the **height of the bigger** horizontal arrangement.

**Comment by N-l1** [comment]
Yes, good point. Check [this](https://www.w3schools.com/howto/howto_css_aspect_ratio.asp) out.

**Comment by KTibow** [comment]
Okay, (note to self and anybody else) here's a slightly changed for simplicity example entry (with `px`).
<details><summary>This is basically the plain YAML minus some stuff</summary>

```yaml
cards:
# First card
 -  icon: 'mdi:lamp'
    show_icon: true
    show_name: false
    style: |
      ha-card {
        margin: 5px;  
        box-shadow: 
          {% if is_state('sun.sun', 'above_horizon') %}                 
            -5px -5px 8px 0 rgba(255,255,255,.5),5px 5px 8px 0 rgba(0,0,0,.03);
          {% elif is_state('sun.sun', 'below_horizon') %}   
            -5px -5px 8px 0 rgba(50, 50, 50,.5),5px 5px 8px 0 rgba(0,0,0,.15);
          {% endif %}                        
      }
    styles:
      card:
        - width: 60px
        - height: 60px
        - border-radius: 15px
        - background-color: var(--primary-background-color)
      icon:
        - color: var(--primary-text-color)
    type: 'custom:button-card'
# Second card
 -  icon: 'mdi:vanity-light'
    show_icon: true
    show_name: false
    style: |
      ha-card {
        margin: 5px;                  
        box-shadow: 
          {% if is_state('sun.sun', 'above_horizon') %}                 
            -5px -5px 8px 0 rgba(255,255,255,.5),5px 5px 8px 0 rgba(0,0,0,.03);
          {% elif is_state('sun.sun', 'below_horizon') %}   
            -5px -5px 8px 0 rgba(50, 50, 50,.5),5px 5px 8px 0 rgba(0,0,0,.15);
          {% endif %}   
      }
    styles:
      card:
        - width: 60px
        - height: 60px
        - border-radius: 15px
        - background-color: var(--primary-background-color)
      icon:
        - color: var(--primary-text-color)
    type: 'custom:button-card'
# Third card
 -  icon: 'mdi:ceiling-light'
    show_icon: true
    show_name: false
    style: |
      ha-card {
        margin: 5px;                  
        box-shadow: 
          {% if is_state('sun.sun', 'above_horizon') %}                 
            -5px -5px 8px 0 rgba(255,255,255,.5),5px 5px 8px 0 rgba(0,0,0,.03);
          {% elif is_state('sun.sun', 'below_horizon') %}   
            -5px -5px 8px 0 rgba(50, 50, 50,.5),5px 5px 8px 0 rgba(0,0,0,.15);
          {% endif %}                             
      }
    styles:
      card:
        - width: 60px
        - height: 60px
        - border-radius: 15px
        - background-color: var(--primary-background-color)
      icon:
        - color: var(--primary-text-color)
    type: 'custom:button-card'
# Fourth card
 -  icon: 'mdi:light-switch'
    show_icon: true
    show_name: false
    style: |
      ha-card {
        margin: 5px;  
        box-shadow: 
          {% if is_state('sun.sun', 'above_horizon') %}                 
            -5px -5px 8px 0 rgba(255,255,255,.5),5px 5px 8px 0 rgba(0,0,0,.03);
          {% elif is_state('sun.sun', 'below_horizon') %}   
            -5px -5px 8px 0 rgba(50, 50, 50,.5),5px 5px 8px 0 rgba(0,0,0,.15);
          {% endif %}     
      }
    styles:
      card:
        - width: 60px
        - height: 60px
        - border-radius: 15px
        - background-color: var(--primary-background-color)
      icon:
        - color: var(--primary-text-color)
    type: 'custom:button-card'
# Fifth card
 -  icon: 'mdi:table-chair'
    show_icon: true
    show_name: false
    style: |
      ha-card {
        margin: 5px;              
        box-shadow: 
          {% if is_state('sun.sun', 'above_horizon') %}                 
            -5px -5px 8px 0 rgba(255,255,255,.5),5px 5px 8px 0 rgba(0,0,0,.03);
          {% elif is_state('sun.sun', 'below_horizon') %}   
            -5px -5px 8px 0 rgba(50, 50, 50,.5),5px 5px 8px 0 rgba(0,0,0,.15);
          {% endif %}     
      }
    styles:
      card:
        - width: 60px
        - height: 60px
        - border-radius: 15px
        - background-color: var(--primary-background-color)
      icon:
        - color: var(--primary-text-color)
    type: 'custom:button-card'
type: horizontal-stack
```
</details>

**Comment by KTibow** [comment]
@N-l1 they look **way** too tiny in width. <details><summary>(Code here, any ideas?)</summary>

```yaml
cards:
  - icon: 'mdi:lamp'
    show_icon: true
    show_name: false
    style: |
      ha-card {
        margin: 5px;  
        box-shadow: 
          {% if is_state('sun.sun', 'above_horizon') %}                 
            -5px -5px 8px 0 rgba(255,255,255,.5),5px 5px 8px 0 rgba(0,0,0,.03);
          {% elif is_state('sun.sun', 'below_horizon') %}   
            -5px -5px 8px 0 rgba(50, 50, 50,.5),5px 5px 8px 0 rgba(0,0,0,.15);
          {% endif %}   
      }
    styles:
      card:
        - width: 50%
        - height: 60px
        - border-radius: 15px
        - background-color: var(--primary-background-color)
      icon:
        - color: var(--primary-text-color)
        - width: 50%
    type: 'custom:button-card'
  - icon: 'mdi:vanity-light'
    show_icon: true
    show_name: false
    style: |
      ha-card {
        margin: 5px;                  
        box-shadow: 
          {% if is_state('sun.sun', 'above_horizon') %}                 
            -5px -5px 8px 0 rgba(255,255,255,.5),5px 5px 8px 0 rgba(0,0,0,.03);
          {% elif is_state('sun.sun', 'below_horizon') %}   
            -5px -5px 8px 0 rgba(50, 50, 50,.5),5px 5px 8px 0 rgba(0,0,0,.15);
          {% endif %}   
      }
    styles:
      card:
        - width: 50%
        - height: 60px
        - border-radius: 15px
        - background-color: var(--primary-background-color)
      icon:
        - color: var(--primary-text-color)
        - width: 50%
    type: 'custom:button-card'
  - icon: 'mdi:ceiling-light'
    show_icon: true
    show_name: false
    style: |
      ha-card {
        margin: 5px;                  
        box-shadow: 
          {% if is_state('sun.sun', 'above_horizon') %}                 
            -5px -5px 8px 0 rgba(255,255,255,.5),5px 5px 8px 0 rgba(0,0,0,.03);
          {% elif is_state('sun.sun', 'below_horizon') %}   
            -5px -5px 8px 0 rgba(50, 50, 50,.5),5px 5px 8px 0 rgba(0,0,0,.15);
          {% endif %}                             
      }
    styles:
      card:
        - width: 50%
        - height: 60px
        - border-radius: 15px
        - background-color: var(--primary-background-color)
      icon:
        - color: var(--primary-text-color)
        - width: 50%
    type: 'custom:button-card'
  - icon: 'mdi:light-switch'
    show_icon: true
    show_name: false
    style: |
      ha-card {
        margin: 5px;  
        box-shadow: 
          {% if is_state('sun.sun', 'above_horizon') %}                 
            -5px -5px 8px 0 rgba(255,255,255,.5),5px 5px 8px 0 rgba(0,0,0,.03);
          {% elif is_state('sun.sun', 'below_horizon') %}   
            -5px -5px 8px 0 rgba(50, 50, 50,.5),5px 5px 8px 0 rgba(0,0,0,.15);
          {% endif %}     
      }
    styles:
      card:
        - width: 50%
        - height: 60px
        - border-radius: 15px
        - background-color: var(--primary-background-color)
      icon:
        - color: var(--primary-text-color)
        - width: 50%
    type: 'custom:button-card'
  - icon: 'mdi:table-chair'
    show_icon: true
    show_name: false
    style: |
      ha-card {
        margin: 5px;              
        box-shadow: 
          {% if is_state('sun.sun', 'above_horizon') %}                 
            -5px -5px 8px 0 rgba(255,255,255,.5),5px 5px 8px 0 rgba(0,0,0,.03);
          {% elif is_state('sun.sun', 'below_horizon') %}   
            -5px -5px 8px 0 rgba(50, 50, 50,.5),5px 5px 8px 0 rgba(0,0,0,.15);
          {% endif %}     
      }
    styles:
      card:
        - width: 50%
        - height: 60px
        - border-radius: 15px
        - background-color: var(--primary-background-color)
      icon:
        - color: var(--primary-text-color)
        - width: 50%
    type: 'custom:button-card'
type: horizontal-stack
```
</details>

**Comment by N-l1** [comment]
Interesting... I was thinking of doing something with [relative lengths](https://www.w3schools.com/cssref/css_units.asp).

**Comment by KTibow** [comment]
Hmm. What I have so far now (WIP):
<details><summary>Hidden for convenience by default</summary>

```yaml
cards:
  - icon: 'mdi:lamp'
    show_icon: true
    show_name: false
    style: |
      ha-card {
        margin: 5px;  
        box-shadow: 
          {% if is_state('sun.sun', 'above_horizon') %}                 
            -5px -5px 8px 0 rgba(255,255,255,.5),5px 5px 8px 0 rgba(0,0,0,.03);
          {% elif is_state('sun.sun', 'below_horizon') %}   
            -5px -5px 8px 0 rgba(50, 50, 50,.5),5px 5px 8px 0 rgba(0,0,0,.15);
          {% endif %}   
      }
    styles:
      card:
        - position: relative
        - height: 60px
        - padding-top: 50%
        - border-radius: 15px
        - background-color: var(--primary-background-color)
      icon:
        - color: var(--primary-text-color)
        - position: absolute
        - top: 0
        - right: 0
        - bottom: 0
        - left: 0
    type: 'custom:button-card'
  - icon: 'mdi:vanity-light'
    show_icon: true
    show_name: false
    style: |
      ha-card {
        margin: 5px;                  
        box-shadow: 
          {% if is_state('sun.sun', 'above_horizon') %}                 
            -5px -5px 8px 0 rgba(255,255,255,.5),5px 5px 8px 0 rgba(0,0,0,.03);
          {% elif is_state('sun.sun', 'below_horizon') %}   
            -5px -5px 8px 0 rgba(50, 50, 50,.5),5px 5px 8px 0 rgba(0,0,0,.15);
          {% endif %}   
      }
    styles:
      card:
        - width: 50%
        - height: 60px
        - border-radius: 15px
        - background-color: var(--primary-background-color)
      icon:
        - color: var(--primary-text-color)
        - width: 50%
    type: 'custom:button-card'
  - icon: 'mdi:ceiling-light'
    show_icon: true
    show_name: false
    style: |
      ha-card {
        margin: 5px;                  
        box-shadow: 
          {% if is_state('sun.sun', 'above_horizon') %}                 
            -5px -5px 8px 0 rgba(255,255,255,.5),5px 5px 8px 0 rgba(0,0,0,.03);
          {% elif is_state('sun.sun', 'below_horizon') %}   
            -5px -5px 8px 0 rgba(50, 50, 50,.5),5px 5px 8px 0 rgba(0,0,0,.15);
          {% endif %}                             
      }
    styles:
      card:
        - width: 50%
        - height: 60px
        - border-radius: 15px
        - background-color: var(--primary-background-color)
      icon:
        - color: var(--primary-text-color)
        - width: 50%
    type: 'custom:button-card'
  - icon: 'mdi:light-switch'
    show_icon: true
    show_name: false
    style: |
      ha-card {
        margin: 5px;  
        box-shadow: 
          {% if is_state('sun.sun', 'above_horizon') %}                 
            -5px -5px 8px 0 rgba(255,255,255,.5),5px 5px 8px 0 rgba(0,0,0,.03);
          {% elif is_state('sun.sun', 'below_horizon') %}   
            -5px -5px 8px 0 rgba(50, 50, 50,.5),5px 5px 8px 0 rgba(0,0,0,.15);
          {% endif %}     
      }
    styles:
      card:
        - width: 50%
        - height: 60px
        - border-radius: 15px
        - background-color: var(--primary-background-color)
      icon:
        - color: var(--primary-text-color)
        - width: 50%
    type: 'custom:button-card'
  - icon: 'mdi:table-chair'
    show_icon: true
    show_name: false
    style: |
      ha-card {
        margin: 5px;              
        box-shadow: 
          {% if is_state('sun.sun', 'above_horizon') %}                 
            -5px -5px 8px 0 rgba(255,255,255,.5),5px 5px 8px 0 rgba(0,0,0,.03);
          {% elif is_state('sun.sun', 'below_horizon') %}   
            -5px -5px 8px 0 rgba(50, 50, 50,.5),5px 5px 8px 0 rgba(0,0,0,.15);
          {% endif %}     
      }
    styles:
      card:
        - width: 50%
        - height: 60px
        - border-radius: 15px
        - background-color: var(--primary-background-color)
      icon:
        - color: var(--primary-text-color)
        - width: 50%
    type: 'custom:button-card'
type: horizontal-stack
```

**Comment by N-l1** [comment]
Some promising results using this code. Seems to work on a smaller phone I tested! 🎉  
<details><summary>Show code</summary>

```yaml
cards:
# First card
 -  icon: 'mdi:lamp'
    show_icon: true
    show_name: false
    style: |
      ha-card {
        margin: 5px;  
        box-shadow: 
          {% if is_state('sun.sun', 'above_horizon') %}                 
            -5px -5px 8px 0 rgba(255,255,255,.5),5px 5px 8px 0 rgba(0,0,0,.03);
          {% elif is_state('sun.sun', 'below_horizon') %}   
            -5px -5px 8px 0 rgba(50, 50, 50,.5),5px 5px 8px 0 rgba(0,0,0,.15);
          {% endif %}                        
      }
      @media only screen and (max-width: 600px) {
         ha-card {
           margin: 3px;  
           box-shadow: 
             {% if is_state('sun.sun', 'above_horizon') %}                 
               -5px -5px 8px 0 rgba(255,255,255,.5),5px 5px 8px 0 rgba(0,0,0,.03);
             {% elif is_state('sun.sun', 'below_horizon') %}   
               -5px -5px 8px 0 rgba(50, 50, 50,.5),5px 5px 8px 0 rgba(0,0,0,.15);
             {% endif %}                        
         }
      }
    styles:
      card:
        - width: 60px
        - height: 60px
        - border-radius: 15px
        - background-color: var(--primary-background-color)
      icon:
        - color: var(--primary-text-color)
    type: 'custom:button-card'
# Second card
 -  icon: 'mdi:vanity-light'
    show_icon: true
    show_name: false
    style: |
      ha-card {
        margin: 5px;  
        box-shadow: 
          {% if is_state('sun.sun', 'above_horizon') %}                 
            -5px -5px 8px 0 rgba(255,255,255,.5),5px 5px 8px 0 rgba(0,0,0,.03);
          {% elif is_state('sun.sun', 'below_horizon') %}   
            -5px -5px 8px 0 rgba(50, 50, 50,.5),5px 5px 8px 0 rgba(0,0,0,.15);
          {% endif %}                        
      }
      @media only screen and (max-width: 600px) {
         ha-card {
           margin: 3px;  
           box-shadow: 
             {% if is_state('sun.sun', 'above_horizon') %}                 
               -5px -5px 8px 0 rgba(255,255,255,.5),5px 5px 8px 0 rgba(0,0,0,.03);
             {% elif is_state('sun.sun', 'below_horizon') %}   
               -5px -5px 8px 0 rgba(50, 50, 50,.5),5px 5px 8px 0 rgba(0,0,0,.15);
             {% endif %}                        
         }
      }
    styles:
      card:
        - width: 60px
        - height: 60px
        - border-radius: 15px
        - background-color: var(--primary-background-color)
      icon:
        - color: var(--primary-text-color)
    type: 'custom:button-card'
# Third card
 -  icon: 'mdi:ceiling-light'
    show_icon: true
    show_name: false
    style: |
      ha-card {
        margin: 5px;  
        box-shadow: 
          {% if is_state('sun.sun', 'above_horizon') %}                 
            -5px -5px 8px 0 rgba(255,255,255,.5),5px 5px 8px 0 rgba(0,0,0,.03);
          {% elif is_state('sun.sun', 'below_horizon') %}   
            -5px -5px 8px 0 rgba(50, 50, 50,.5),5px 5px 8px 0 rgba(0,0,0,.15);
          {% endif %}                        
      }
      @media only screen and (max-width: 600px) {
         ha-card {
           margin: 3px;  
           box-shadow: 
             {% if is_state('sun.sun', 'above_horizon') %}                 
               -5px -5px 8px 0 rgba(255,255,255,.5),5px 5px 8px 0 rgba(0,0,0,.03);
             {% elif is_state('sun.sun', 'below_horizon') %}   
               -5px -5px 8px 0 rgba(50, 50, 50,.5),5px 5px 8px 0 rgba(0,0,0,.15);
             {% endif %}                        
         }
      }
    styles:
      card:
        - width: 60px
        - height: 60px
        - border-radius: 15px
        - background-color: var(--primary-background-color)
      icon:
        - color: var(--primary-text-color)
    type: 'custom:button-card'
# Fourth card
 -  icon: 'mdi:light-switch'
    show_icon: true
    show_name: false
    style: |
      ha-card {
        margin: 5px;  
        box-shadow: 
          {% if is_state('sun.sun', 'above_horizon') %}                 
            -5px -5px 8px 0 rgba(255,255,255,.5),5px 5px 8px 0 rgba(0,0,0,.03);
          {% elif is_state('sun.sun', 'below_horizon') %}   
            -5px -5px 8px 0 rgba(50, 50, 50,.5),5px 5px 8px 0 rgba(0,0,0,.15);
          {% endif %}                        
      }
      @media only screen and (max-width: 600px) {
         ha-card {
           margin: 3px;  
           box-shadow: 
             {% if is_state('sun.sun', 'above_horizon') %}                 
               -5px -5px 8px 0 rgba(255,255,255,.5),5px 5px 8px 0 rgba(0,0,0,.03);
             {% elif is_state('sun.sun', 'below_horizon') %}   
               -5px -5px 8px 0 rgba(50, 50, 50,.5),5px 5px 8px 0 rgba(0,0,0,.15);
             {% endif %}                        
         }
      }
    styles:
      card:
        - width: 60px
        - height: 60px
        - border-radius: 15px
        - background-color: var(--primary-background-color)
      icon:
        - color: var(--primary-text-color)
    type: 'custom:button-card'
# Fifth card
 -  icon: 'mdi:table-chair'
    show_icon: true
    show_name: false
    style: |
      ha-card {
        margin: 5px;  
        box-shadow: 
          {% if is_state('sun.sun', 'above_horizon') %}                 
            -5px -5px 8px 0 rgba(255,255,255,.5),5px 5px 8px 0 rgba(0,0,0,.03);
          {% elif is_state('sun.sun', 'below_horizon') %}   
            -5px -5px 8px 0 rgba(50, 50, 50,.5),5px 5px 8px 0 rgba(0,0,0,.15);
          {% endif %}                        
      }
      @media only screen and (max-width: 600px) {
         ha-card {
           margin: 3px;  
           box-shadow: 
             {% if is_state('sun.sun', 'above_horizon') %}                 
               -5px -5px 8px 0 rgba(255,255,255,.5),5px 5px 8px 0 rgba(0,0,0,.03);
             {% elif is_state('sun.sun', 'below_horizon') %}   
               -5px -5px 8px 0 rgba(50, 50, 50,.5),5px 5px 8px 0 rgba(0,0,0,.15);
             {% endif %}                        
         }
      }
    styles:
      card:
        - width: 60px
        - height: 60px
        - border-radius: 15px
        - background-color: var(--primary-background-color)
      icon:
        - color: var(--primary-text-color)
    type: 'custom:button-card'
type: horizontal-stack
```
</details>
